Herculien Build Guide
=====================

This guide is intended to get you through the basics of assembling the Herculien
3D Printer.  It is a living document so be aware that the procedure is subject to change.

Pictures are included for clarity and where necessary YouTube videos will be embedded.

The guide will be structured around the subassemblies that are listed in the BOM however
to save time later we will include parts/fasteners from other subassemblies where
needed.

Tools Required
==============

 * 2.5mm Hex Wrench
 * 3mm Hex Wrench
 * Bubble Level (for leveling the Z Gantry)
 * Multimeter
 * Saw for cutting aluminum
 * Marker
 * Masking tape
 * Metric tap set (only a 5mm tap is required)
 * Drill
 * 1mm drill bit or equivalent imperial standard bit (This is just used for drilling pilot holes so it doesn't have to be precise but needs to be small enough to fit in the drill guide)
 * 5mm drill bit
 * 8mm drill bit
 * 7/8" drill bit
 * 1/2" End mill
 
Metal Preparation
=================

 1. Using the 5mm x .8 thread tap, tap all of the regular 20x80 extrusion end holes
    * Use cutting oil
    * Go Slow
    * You can either do by hand or using a drill.  If you use a drill you must take it VERY slow as you can easily break the tap bit.
 
    Example:
    [![How to tap an aluminum extrusion](http://img.youtube.com/vi/5AQUodkQZbg/0.jpg)](https://www.youtube.com/watch?v=5AQUodkQZbg)

Main Frame
==========

## Parts required:

 * 9x 20x80 Aluminum Extrusions cut to 569.5mm
 * 4x 20x20 Aluminum Extrusions cut to 609.5mm
 * 2x 20x80 V-Slot Aluminum Extrusions
 * 102x T-Slot Nuts
 * 160x M5 x 10mm Button Head Screws
 * 6x M5 x 8mm Flat Head Socket Cap Screws
 * 16x M5 x 8mm Button Head Screws

## Bottom Assembly

 1. The BOM lists a 1 meter section of V-Slot, if you haven't cut the V-Slot you should do that now.
    * To cut the V-Slot you can use any saw or cutting wheel capable of cutting through a 20x80 extrusion.
    * I was successful doing this with an angle grinder and metal cutoff blade.
    * While you should be careful to cut this as straight as possible it isn't necessary to
      cut this exactly straight.  The factory cut ends are straight and those will be what is used
      to square the verticals for the Z Gantry rails to be perpendicular to the center rail.
    
 2. Using your marker and masking tape, label each of the 9 20x80 extrusions using the following labels.  These labels aren't necessary
    but will make things easier in the following steps to keep things in order.  It also helps to indicate which end it up, I use arrows
    on the masking labels.
    
    * Top Front
    * Top Rear
    * Top Right
    * Top Left
    * Bottom Front
    * Bottom Rear
    * Bottom Right
    * Bottom Left
    * Center Rail
    
    Example:
    ![alt text](./Photos/IMG_20150220_141237.jpg "20x80 Extrusion Label")

 3. Using your marker and masking tape, label each of the 4 20x20 extrusions with the following labels.
    * Front Right
    * Rear Right
    * Front Left
    * Rear Left
    
    Example:
    ![alt text](./Photos/IMG_20150220_141252.jpg "20x20 Extrusion Label")
  
 4. Locate the 4 20x20 extrusions to be used at vertical supports for the main frame.
  
 5. Using 3 M5x8mm button head screws and 2 T-Slot nuts attach the 20x20 extrusion drill guide to one end of the extrusion.
  
     Examples: ![alt text](./Photos/1424094009658.jpg "20x20 Extrusion Drill Guide 1")
               ![alt text](./Photos/1424094010046.jpg "20x20 Extrusion Drill Guide 2")
  
 6. Using the 5mm drill bit, drill all 8 holes using the raised drill guide holes.
     
     Result: ![alt text](./Photos/IMG_20150220_155826.jpg "20x20 Extrusion drilled")
  
 7. Repeat this process for the other end of the extrusion and then for the remaining 3 verticals.
  
 8.  Locate the two 20x80 extrusions marked "Bottom Right" and "Bottom Left"
  
 9.  Beginning with one of these, use 4 M5x8mm button head screws and 4 T-Slot nuts attach the 20x80 8 hole drill guide but do not tighten down.
  
 10. Measure from one end of the extrusion 215mm and slide the drill guide over until the very edge of it lines up with that line.
      
      Drawing: ![alt text](./Drawings/Location_Of_Vertical_Z-Bed_Vslot_Guides.jpg "Drawing")
      
 11. Tighten the drill guide down and double check your measurement until it is **EXACT**
  
 12. Drill all 8 holes using the 5mm drill bit.
  
 13. Repeat for the other piece making sure your measurements are **EXACT**
  
 14. Orient the two pieces standing on their 20mm side on the floor or other flat surface keeping the perspective that you are looking at the completed chassis from the front.  e.g. "Bottom Left" goes to your left and "Bottom right" goes to your right.
  
 15. Ensure the 2 rows of holes you just drilled are nearest the top of the extrusion and the side measured 215mm from edge to the drill guide is placed facing you.
  
 16. Now using the masking tape and markers label the inside face of each so that the orientation is clear.
      
      Result: ![alt text](./Photos/IMG_20150220_161343.jpg "20x80mm Extrusion Bottom Right")
              ![alt text](./Photos/IMG_20150220_161352.jpg "20x80mm Extrusion Bottom Left")
              ![alt text](./Photos/IMG_20150220_161413.jpg "20x80mm Extrusions properly oriented")
   
 17. Locate the 20x80 extrusion pieces marked "Bottom Front" and "Bottom Rear"
 
 18. Orient the pieces on the floor or flat surface with the 2 bottom left and right extrusions with one 20mm side lying flat on the surface.
 
     Example: ![alt text](./Photos/IMG_20150220_175620.jpg "20x80mm Extrusions oriented correctly")
 
 19. Using the marker and masking tape, label the inside of each and use an drawn arrow to indicate which way is up.
 
 20. On the piece marked "Bottom Rear" insert 2 T-Slot nuts in the top row of the innermost side.  Insert 4 T-Slot nuts in the row below that.  Insert 2 T-Slot nuts in the row below that.  Use M5x10mm button head screws hand tightened to hold them in place.
 
     Example: ![alt text](./Photos/IMG_20150220_175640.jpg "Bottom Rear Extrusion Nuts Installed")

 21. On the piece marked "Bottom Front" insert 1 T-Slot nut on the top row of the innermost side.  Insert 1 T-Slot nut in the row below that.  Use M5x10mm button head screws, hand tightened, to hole them in place.
 
     Example: ![alt text](./Photos/IMG_20150220_175717.jpg "Bottom Front Extrusion Nuts Installed")
 
 22. On the piece marked "Bottom Right" insert 3 T-Slot nuts on the top row and use M5x10mm button top screws, hand tightened, to hold them in place.
     
     Example: ![alt text](./Photos/IMG_20150220_175657.jpg "Bottom Right Extrusion Nuts installed")
 
 23. Thread M5x10mm button head screws into each of the 4 holes on each end of the 4 bottom 20x80mm extrusions placed on the flat surface from earlier.  Thread the screws in until there is only approximately 3-4mm of thread showing.
 
     Example: ![alt text](./Photos/IMG_20150220_183040.jpg "Extrusion end screws installed")
 
 24. Locate the 20x80 extrusion labeled "Center Rail"
 
 25. Thread M5x10mm button head screws in the 4 holes in each of the ends of the "Center Rail" leaving only about 3-4mm of thread showing.
 
 26. Slide one side of the center rails button head screws in the bottom left 20x80 extrusion's second from the top slot and visually line it up with the 4 holes that are drilled in the bottom left piece.
     
     Example: ![alt text](./Photos/IMG_20150220_215620.jpg "Attaching Center Rail to Bottom Left extrusion")
     
 27. Using your measuring tool measure 215mm from the front edge of the "Bottom Left" 20x80mm extrusion to the edge of the "Center Rail".
     
     Example: ![alt text](./Photos/IMG_20150220_215705.jpg "Measuing Center Rail Placement")
 
 28. Passing the 2.5mm hex wrench through the holes in the opposite side of the "Front Left" extrusion tighten the button head screws on the "Center Rail" locking them in place.  Be sure to double check your measurements.
 
     Example: ![alt text](./Photos/IMG_20150220_215904.jpg "Tightening the Center Rail")
 
 29. The Front of the Center rail is now the side measured 215mm away from the front edge of the supporting extrusion.  If it helps you to keep track of these things use the masking tape and marker to label the side that is front.
 
 30. On the front side of the center rail insert 2 T-Slot nuts and use 2 M5x10mm button head screws, hand tightened, to hold them in place. On the top of the "Center Rail" in the first of four slots insert 4 T-Slot nuts with M5x10mm button head screws to hold them in place.  Do the same for the second from the front edge slot.  Skip the third slot and on the foourth slot from the front insert 2 T-Slot Nuts with 2 M5x10mm button head screws to hole them in place.
     
     Example: ![alt text](./Photos/IMG_20150220_215946.jpg "Setup T-Slot nuts for later mounting things")
     
 31. Now repeat step 26-28 for the other side of the Center Rail, securing the Center Rail to the "Bottom Right" 20x80mm extrusion.
 
     Example: ![alt text](./Photos/IMG_20150220_220036.jpg "Finished Center Rail")
 
 32. Locate the 2 V-Slot 20x80 extrusions measuring 489.5mm.  These do not need labels as they are identical and either will work on either side.
 
 33. With one of the V-Slot extrusions on one 80mm side nearest the factory straight cut insert 1 T-Slot nut in each slot and hand thread 1 M5x8mm button head screw for each T-Slot nut but do not tighten.
 
     Example: ![alt text](./Photos/IMG_20150220_230648.jpg "V-Slot extrusion with T-Slot nuts prepped")
 
 34. Slide the button head screws in the top slot of the "Bottom Left" 20x80mm extrusion.  I find it's easier to stand the "Bottom Left", "Center Rail" and "Bottom Right" assembled pieces on one end so that it looks like an "H".
 
     Example: ![alt text](./Photos/IMG_20150220_230750.jpg "Inserting V-Slot button head screws into 20x80mm T-Slot extrusion")
 
 35. Carefully slide this assembly down the rail and place it sitting on top of the Center Rail extrusion and make sure the edges of the V-Slot are flush with the Center Rail extrusion on both sides.
 
 36. Passing the 2.5mm hex wrench through the holes on the opposite side of the "Bottom Left" extrusion tighten down each screw.
 
 37. Double check your measurements and ensure that the front 20mm edge of the V-Slot extrusion is exactly 215mm away from the front edge of the "Bottom Left" extrusion.
 
     Example: ![alt text](./Photos/IMG_20150220_230940.jpg "V-Slot vertical in place")
 
 38. Repeat steps 33-37 for the "Bottom Right" 20x80mm extrusion using the remaining V-Slot extrusion.
 
 39. Locate the 4 20x20 extrusions that are 609.5mm long.  These are the verticals to hold everything upright.
 
 40. Find the 20x80 extrusions marked "Bottom Front" and "Bottom Left" and use the 20x20 vertical marked "Front Left" for the next step.
     
 41. Slide button head screws at the end of the "Bottom Front" 20x80 extrusion's left side into the slot of the 20x20mm extrusion and then do the same with the 20x80mm "Bottom Left" extrusion at a right angle to the "Bottom Front" extrusion.  See picture for example.
     
     Example: ![alt text](./Photos/IMG_20150214_123942.jpg "Building a corner")
 
 42. Use your 2.5mm hex wrench to tighten the button head screws by passing the wrench through the holes drilled in the 20x20 extrusion.  **ENSURE** the bottom of the 20x80 extrusions are flush with the bottom of the vertical 20x20 extrusion.
     
     Example: ![alt text](./Photos/IMG_20150220_225212.jpg "Corner Vertical installed")
     
 43. Repeat steps 25-27 for the 4 corners paying close attention to use the correct vertical per corner.  If you use the wrong one, you can switch their labels once you're finished.  The labeling matters in the coming steps.
     
     Example: ![alt text](./Photos/IMG_20150220_232801.jpg "All corners done, bottom assembly complete")
 
## Top Assembly

 1. Locate the 20x80mm extrusion marked "Top Front" and lay it flat on one of it's 80mm sides in front of you.
 
 2. We will assume this is now the inside of the top front extrusion and the 20mm side furthest from you is the side that will be at the top of the finished chassis., mark it with the tape and marker.
    
    Example: ![alt text](./Photos/IMG_20150221_190037.jpg "Top Front extrusion properly labeled")
    
 3. Locate Corner Bearing Bracket B, this is a printed part.
 
 4. Place Corner Bearing Bracket B on the right side of the 80mm side facing you with the bearing support hole closest to the edge of the printed part laying flat on the extrusion.  Make sure the printed part is lined up against the right edge with the opposing bearing support hole vertical and flush with the edge.
 
    Example: ![alt text](./Photos/IMG_20150221_190514.jpg "Corner Bearing Bracket B placed properly on extrusion")
 
 5. Locate the printed extrusion drill guide shown below.
 
    Example: ![alt text](./Photos/IMG_20150221_190620.jpg "Pilot hole drill guide")
 
 6. Place this drill guide under the Corner Bearing bracket and make note of the hole you should be drilling, it will be in the center of the hole in the corner bearing bracket.  It should be the top most pilot hole on the drill guide.
 
    Example: ![alt text](./Photos/IMG_20150221_190743.jpg "Drill guide placed under bearing bracket")
             ![alt text](./Photos/IMG_20150221_190750.jpg "Drill this hole")
 
 7. Set the Corner Bearing Bracket B aside for later use.
 
 8. Using 4 M5x10mm button head screws secure the drill guide to the right edge of the extrusion.
 
    Example: ![alt text](./Photos/IMG_20150221_191033.jpg "Screws in the 4 holes on this side")
 
 9. Using 2 T-Slot nuts and 2 M5x10mm button head Screws secure the 2 holes on the upper face of the drill guide to the extrusion.
 
    Example: ![alt text](./Photos/IMG_20150221_191047.jpg "Secure these holes")
 
 10. If you have access to a drill press you would be best served using it for the next drilling steps but a hand drill used carefully will suffice.
 
 11. Drill the top most pilot hole using a small bit.
 
 12. Remove the drill guide and set the screws and T-Slot nuts aside.
 
 13. Using a slightly larger bit (I used a 5mm bit) drill out the pilot hole.
 
 14. Using your 1/2" end mill drill the final hole through the extrusion.
 
     Example: ![alt text](./Photos/IMG_20150221_191712.jpg "Finished 1/2 inch hole")
 
 15. At this time you can choose to use a round file to clean up the drilled hole.
 
 16. Lay the extrusion down on a table or the floor in front of you with the labeled inside facing you and the top 20mm side facing away from you.
 
     Example: ![alt text](./Photos/IMG_20150221_191836.jpg "Orient the extrusion correctly")
 
 17. In the slot closest you insert 8 T-Slot nuts and hand tighten 1 M5x10mm button head screw into each so that the T-Slot nuts do not slide around.
 
 18. In the slot above that insert 4 T-Slot nuts and hand tighten 1 M5x10mm button head screw into each so that the T-Slot nuts do not slide around.
 
 19. In the slot above that insert 2 T-Slot nuts and hand tighten 1 M5x10mm button head screw into each so that the T-Slot nuts do not slide around.
 
 20. In the top slot insert 4 T-Slot nuts and hand tighten 1 M5x10mm button head screw into each so that the T-Slot nuts do not slide around.

     Example: ![alt text](./Photos/IMG_20150221_192157.jpg "Inserted T-Slot nuts")
 
 21. Thread M5x10mm button head screws into the 4 holes on each end of the extrusion.
 
     Example: ![alt text](./Photos/IMG_20150221_192449.jpg "Ends threaded")
 
 22. Set this extrusion aside for later use.
 
 23. Locate the 20x80mm extrusion labeled "Top Rear" and lay it flat on one of it's 80mm sides in front of you.
 
 24. We will assume this is now the inside of the top rear extrusion and the 20mm side furthest from you is the side that will be at the top of the finished chassis., mark it with the tape and marker.
 
     Example: ![alt text](./Photos/IMG_20150224_202313.jpg "Top Rear properly labeled")
 
 25. Locate Corner Bearing Bracket B, this is a printed part.
 
 26. Place Corner Bearing Bracket B on the right side of the 80mm side facing you with the bearing support hole closest to the edge of the printed part laying flat on the extrusion.  Make sure the printed part is lined up against the right edge with the opposing bearing support hole vertical and flush with the edge.
 
     Example: ![alt text](./Photos/IMG_20150221_190514.jpg "Corner Bearing Bracket B placed properly on extrusion")
     
 27. Locate the printed extrusion drill guide shown below.
 
     Example: ![alt text](./Photos/IMG_20150221_190620.jpg "Pilot hole drill guide")
 
 28. Place this drill guide under the Corner Bearing bracket and make note of the hole you should be drilling, it will be in the center of the hole in the corner bearing bracket.  It should be the top most pilot hole on the drill guide.
     
     Example: ![alt text](./Photos/IMG_20150221_190743.jpg "Drill guide placed under bearing bracket")
             ![alt text](./Photos/IMG_20150221_190750.jpg "Drill this hole")
     
 29. Set the Corner Bearing Bracket B aside for later use.
 
 30. Using 4 M5x10mm button head screws secure the drill guide to the right edge of the extrusion.
 
    Example: ![alt text](./Photos/IMG_20150221_191033.jpg "Screws in the 4 holes on this side")
 
 31. Using 2 T-Slot nuts and 2 M5x10mm button head Screws secure the 2 holes on the upper face of the drill guide to the extrusion.
 
    Example: ![alt text](./Photos/IMG_20150221_191047.jpg "Secure these holes")
 
 32. If you have access to a drill press you would be best served using it for the next drilling steps but a hand drill used carefully will suffice.
 
 33. Drill the top most pilot hole using a small bit.
 
 34. Remove the drill guide and set the screws and T-Slot nuts aside.
 
 35. Using a slightly larger bit (I used a 5mm bit) drill out the pilot hole.
 
 36. Using your 1/2" end mill drill the final hole through the extrusion.
 
     Example: ![alt text](./Photos/IMG_20150221_191712.jpg "Finished 1/2 inch hole")
 
 37. At this time you can choose to use a round file to clean up the drilled hole.
 
 38. Lay the extrusion down on a table or the floor in front of you with the labeled inside facing you and the top 20mm side facing away from you.
 
     Example: ![alt text](./Photos/IMG_20150221_191836.jpg "Orient the extrusion correctly")
 
 39. In the slot closest you insert 4 T-Slot nuts and hand tighten 1 M5x10mm button head screw into each so that the T-Slot nuts do not slide around.
 
 40. In the slot above that insert 4 T-Slot nuts and hand tighten 1 M5x10mm button head screw into each so that the T-Slot nuts do not slide around.
 
 41. In the slot above that insert 2 T-Slot nuts and hand tighten 1 M5x10mm button head screw into each so that the T-Slot nuts do not slide around.
 
 42. In the top slot insert 4 T-Slot nuts and hand tighten 1 M5x10mm button head screw into each so that the T-Slot nuts do not slide around.

     Example: ![alt text](./Photos/IMG_20150224_204925.jpg "T-Slot nuts properly installed")
 
 43. Thread M5x10mm button head screws into the 4 holes on each end of the extrusion.
 
     Example: ![alt text](./Photos/IMG_20150221_192449.jpg "Ends threaded")
 
 44. Set this extrusion aside for later use.
 
 45. Find the 20x80mm extrusion labeled "Top Left" and lay it flat on one of it's 80mm sides in front of you.
 
 46. We will assume this is now the inside of the top rear extrusion and the 20mm side furthest from you is the side that will be at the top of the finished chassis., mark it with the tape and marker.
 
     Example: ![alt text](./Photos/IMG_20150224_202313.jpg "Top Left properly labeled")
  
 47. Locate Corner Bearing Bracket A, this is a printed part.
 
 48. Place Corner Bearing Bracket A on the right side of the 80mm side facing you with the bearing support hole closest to the edge of the printed part laying flat on the extrusion.  Make sure the printed part is lined up against the right edge with the opposing bearing support hole vertical and flush with the edge.
 
     Example: ![alt text](./Photos/IMG_20150225_081235.jpg "Corner Bearing Bracket A placed correctly")
     
 49. Locate the printed extrusion drill guide shown below.
 
     Example: ![alt text](./Photos/IMG_20150221_190620.jpg "Pilot hole drill guide")
 
 50. Place this drill guide under the Corner Bearing bracket and make note of the hole you should be drilling, it will be in the center of the hole in the corner bearing bracket.  It should be the second pilot hole from the bottom on the drill guide.
     
     Example: ![alt text](./Photos/IMG_20150225_081324.jpg "Drill guide placed correctly")
              ![alt text](./Photos/IMG_20150225_081339.jpg "Drill this hole")
     
 51. Set the Corner Bearing Bracket A aside for later use.
 
 52. Using 4 M5x10mm button head screws secure the drill guide to the right edge of the extrusion.
 
    Example: ![alt text](./Photos/IMG_20150221_191033.jpg "Screws in the 4 holes on this side")
 
 53. Using 2 T-Slot nuts and 2 M5x10mm button head Screws secure the 2 holes on the upper face of the drill guide to the extrusion.
 
    Example: ![alt text](./Photos/IMG_20150221_191047.jpg "Secure these holes")
 
 54. If you have access to a drill press you would be best served using it for the next drilling steps but a hand drill used carefully will suffice.
 
 55. Drill the top most pilot hole using a small bit.
 
 56. Remove the drill guide and set the screws and T-Slot nuts aside.
 
 57. Using a slightly larger bit (I used a 5mm bit) drill out the pilot hole.
 
 58. Using your 1/2" end mill drill the final hole through the extrusion.
 
     Example: ![alt text](./Photos/IMG_20150225_081509.jpg "1/2 inc hole drilled")
 
 59. At this time you can choose to use a round file to clean up the drilled hole.
 
 60. Locate Corner Bearing Bracket B, this is a printed part.
 
 61. Place Corner Bearing Bracket B on the left side of the 80mm side facing you with the bearing support hole closest to the edge of the printed part laying flat on the extrusion.  Make sure the printed part is lined up against the right edge with the opposing bearing support hole vertical and flush with the edge.
 
     Example: ![alt text](./Photos/IMG_20150225_081620.jpg "Corner Bearing Bracket B placed correctly")
     
 62. Locate the printed extrusion drill guide shown below.
 
     Example: ![alt text](./Photos/IMG_20150221_190620.jpg "Pilot hole drill guide")
 
 63. Place this drill guide under the Corner Bearing bracket and make note of the hole you should be drilling, it will be in the center of the hole in the corner bearing bracket.  It should be the second pilot hole from the bottom on the drill guide.
     
     Example: ![alt text](./Photos/IMG_20150225_081647.jpg "Drill guide placed under the bearing bracket")
              ![alt text](./Photos/IMG_20150225_081704.jpg "Drill this hole")
     
 64. Set the Corner Bearing Bracket B aside for later use.
 
 65. Using 4 M5x10mm button head screws secure the drill guide to the right edge of the extrusion.
 
    Example: ![alt text](./Photos/IMG_20150225_083801.jpg "Screws in the 4 holes on the side")
 
 66. Using 2 T-Slot nuts and 2 M5x10mm button head Screws secure the 2 holes on the upper face of the drill guide to the extrusion.
 
    Example: ![alt text](./Photos/IMG_20150225_083814.jpg "Secure these holes")
 
 67. If you have access to a drill press you would be best served using it for the next drilling steps but a hand drill used carefully will suffice.
 
 68. Drill the top most pilot hole using a small bit.
 
 69. Remove the drill guide and set the screws and T-Slot nuts aside.
 
 70. Using a slightly larger bit (I used a 5mm bit) drill out the pilot hole.
 
 71. Using your 1/2" end mill drill the final hole through the extrusion.
 
     Example: ![alt text](./Photos/IMG_20150225_081714.jpg "1/2 inch hole drilled")
 
 72. Locate the drill guide shown below
 
     Example: ![alt text](./Photos/IMG_20150225_084501.jpg "V-Slot support drill guide")
 
 73. With the 20x80mm Top Left extrusion sitting on the table in front of you with the inside side facing up and the 20mm side labeled as the top of the extrusion facing away from you place the drill guide on the bottom edge as shown.
 
     Example: ![alt text](./Photos/IMG_20150225_084518.jpg "Drill guide placed this way")
 
 74. Measure **exactly** 215mm from the left edge of the extrusion  and slide the edge of the drill guide to that point.
 
     Example: ![alt text](./Photos/IMG_20150225_084710.jpg "Measuring 215mm to edge of the drill guide")
 
 75. Using 4 T-Slot nuts and 1 M5x8mm button head screw per nut secure the drill guide holes on this side taking special care to preserve the 215mm from the left edge.
 
     Example: ![alt text](./Photos/IMG_20150225_084739.jpg "Secure these holes")
 
 76. You can optionally secure 2 to 4 of the holes on the top side of the drill guide but I've found that it isn't 100% necessary, I did this both ways and the result came out the same.
 
 77. Drill these 4 holes with a 5mm drill bit.
 
     Example: ![alt text](./Photos/IMG_20150225_084748.jpg "Drill these holes")
              ![alt text](./Photos/IMG_20150225_084807.jpg "Holes drilled")
 
 78. Place the 20x80mm Top Left extrusion sitting on the table in front of you with the inside side facing up and the 20mm side labeled as the top of the extrusion facing away from you.
 
 79. Locate 4 T-Slot Nuts and 4 M5x8mm button head screws.
 
 80. Thread the 8mm screws into the T-Slot nuts as shown below.
 
     Example: ![alt text](./Photos/IMG_20150225_090755.jpg "8mm screws and T-Slot nuts")
 
 81. In the slot of the extrusion closest to you slide the 4 button head screw tops in like this.
 
     Example: ![alt text](./Photos/IMG_20150225_090924.jpg "Center support screws inserted")
 
 82. On each side of these 4 screws insert 2 T-slot nuts and secure them with 1 M5x10mm button head screw each, hand tightened to keep them from sliding.
 
 83. In the slot above this insert 2 T-Slot nuts and secure them with 1 M5x10mm button head screw each, hand tightened to keep them from sliding.
 
 84. In the slot above this insert 4 T-Slot nuts and secure them with 1 M5x10mm button head screw each, hand tightened to keep them from sliding.
 
 85. In the top most slot insert 4 T-Slot nuts and secure them with 1 M5x10mm button head screw each, hand tightened to keep them from sliding.
 
 86. Thread M5x10mm button head screws into the 4 holes on each end of the extrusion.
 
     Example: ![alt text](./Photos/IMG_20150221_192449.jpg "Ends threaded")
 
 87. The end result should look like this.
 
     Example: ![alt text](./Photos/IMG_20150225_081726.jpg "Top Left 20x80mm extrusion finished")
 
 88. Set this extrusion aside for later use.
 
 89. Locate the 20x80mm extrusion marked "Top Right" and lay it flat on one of it's 80mm sides in front of you.
 
 90. We will assume this is now the inside of the top rear extrusion and the 20mm side furthest from you is the side that will be at the top of the finished chassis., mark it with the tape and marker.
 
     Example: ![alt text](./Photos/IMG_20150225_211121.jpg "Top Right properly labeled")
 
 91. Locate the drill guide shown below
 
     Example: ![alt text](./Photos/IMG_20150225_084501.jpg "V-Slot support drill guide")
 
 92. With the 20x80mm Top Right extrusion sitting on the table in front of you with the inside side facing up and the 20mm side labeled as the top of the extrusion facing away from you place the drill guide on the bottom edge as shown.
 
     Example: ![alt text](./Photos/IMG_20150225_213752.jpg "Drill guide placed this way")
 
 93. Measure **exactly** 215mm from the right edge of the extrusion and slide the edge of the drill guide to that point.
 
     Example: ![alt text](./Photos/IMG_20150225_215111.jpg "Measuring 215mm to edge of the drill guide")
 
 94. Using 4 T-Slot nuts and 1 M5x8mm button head screw per nut secure the drill guide holes on this side taking special care to preserve the 215mm from the left edge.
 
     Example: ![alt text](./Photos/IMG_20150225_084739.jpg "Secure these holes")
 
 95. You can optionally secure 2 to 4 of the holes on the top side of the drill guide but I've found that it isn't 100% necessary, I did this both ways and the result came out the same.
 
 96. Drill these 4 holes with a 5mm drill bit.
 
     Example: ![alt text](./Photos/IMG_20150225_084748.jpg "Drill these holes")
              ![alt text](./Photos/IMG_20150225_215219.jpg "Holes drilled")
 
 97. Place the 20x80mm Top Left extrusion sitting on the table in front of you with the inside side facing up and the 20mm side labeled as the top of the extrusion facing away from you.
 
 98. Locate 4 T-Slot Nuts and 4 M5x8mm button head screws.
 
 99. Thread the 8mm screws into the T-Slot nuts as shown below.
 
     Example: ![alt text](./Photos/IMG_20150225_090755.jpg "8mm screws and T-Slot nuts")
 
 100. In the slot of the extrusion closest to you slide the 4 button head screw tops in like this.
 
     Example: ![alt text](./Photos/IMG_20150225_215600.jpg "Center support screws inserted")
 
 101. On each side of these 4 screws insert 2 T-slot nuts and secure them with 1 M5x10mm button head screw each, hand tightened to keep them from sliding.
 
 102. In the slot above this insert 2 T-Slot nuts and secure them with 1 M5x10mm button head screw each, hand tightened to keep them from sliding.
 
 103. In the slot above this insert 4 T-Slot nuts and secure them with 1 M5x10mm button head screw each, hand tightened to keep them from sliding.
 
 104. In the top most slot insert 6 T-Slot nuts and secure them with 1 M5x10mm button head screw each, hand tightened to keep them from sliding.
 
 105. The end result should look like this.
 
     Example: ![alt text](./Photos/IMG_20150225_215713.jpg "Top Right 20x80mm extrusion finished")
 
 106. Flip the extrusion over so that the outside side is facing up.
 
      Example: ![alt text](./Photos/IMG_20150225_220609.jpg "Top Right outside labeled correctly")
 
 107. In the slot closest to you, the bottom most slot, insert 5 T-Slot nuts and secure them with 1 M5x10mm button head screw each, hand tightened to keep them from sliding.
 
 108. In the top most slot on the outer side insert 5 T-Slot nuts and secure them with 1 M5x10mm button head screw each, hand tightened to keep them from sliding.
 
 109. Thread M5x10mm button head screws into the 4 holes on each end of the extrusion.
 
     Example: ![alt text](./Photos/IMG_20150221_192449.jpg "Ends threaded")
 
 110. The end result should look like this.
 
      Example: ![alt text](./Photos/IMG_20150225_221002.jpg "T-Slot nuts setup on outside of Top Rear")
 
 110. Set this extrusion aside for later use.

## Power supply and switch plate

 1. Locate the printed part "Outlet Switch and Network Mount" and the Electrical fused plug part ordered from the BOM.
 
    Example: ![alt text](./Photos/IMG_20150228_130830.jpg "Outlet Switch and Network Mount printed part")
 
 2. Slide the fused plug into the outlet switch and network mount printed part.
 
    Example: ![alt text](./Photos/IMG_20150228_130840.jpg "Fused plug goes in this hole... obviously.")
 
 3. Mark the hole on either side of the fused plug for drilling and remove the fused plug from the printed part.
 
 4. Using a 3mm or equivalent drill bit, drill the 2 holes.
 
 5. Slide the fused plug back into the outlet switch and network mount plate and line up the holes in the fused plug with the drilled holes.
 
 6. Using an M3x12mm socket cap screw and an M3 lock nut secure the fused switch to the printed part for each hole.
 
    Example: ![alt text](./Photos/IMG_20150228_133910.jpg "Fused plug secured in outlet switch mount")
 
 7. On the "Bottom Right" 20x80mm extrusion remove 2 of the M5x10mm button head screws from the 2 T-slot nuts closest to the right rear corner.
 
 8. Slide all T-Slot nuts out of the way of the rear corner to make it easier to slide them into place later.
 
 9. With the outlet switch printed part laying down on a flat surface with the switch side up, locate the 2 holes on the right side.
 
    Example: ![alt text](./Photos/IMG_20150228_133046.jpg "These holes")
 
 10. Insert 1 M5x8mm button head screw in each hole from the inside.
 
     Example: ![alt text](./Photos/IMG_20150228_133139.jpg "Screws here.")
 
 11. Thread 1 T-Slot nut on each screw to prepare the switch for securing into the rear right corner 20x20mm vertical extrusion.
 
     Example: ![alt text](./Photos/IMG_20150228_133327.jpg "T-Slot nuts threaded properly")
 
 12. Slide the T-Slot nuts in the rear right vertical extrusion on the face that is facing the front of the chassis.
 
     Example: ![alt text](./Photos/IMG_20150228_133442.jpg "Slide nuts into the rear right vertical extrusion.")
 
 13. Slide the printed part all the way down to the bottom and secure the 2 button head screws from the inside.
 
 14. Using a long hex wrench slide 1 T-Slot nut under the outlet switch and network mount printed part until it lines up with the rear most hole.
 
 15. Use 1 M5x8mm button head screw to secure this T-Slot nut.
 
 16. Repeat steps 14-15 for the other bottom hole of the outlet switch mount.
 
     Example: ![alt text](./Photos/IMG_20150228_133910.jpg "Fused plug and outlet switch plate mounted.")
 
 17. Locate the power supply and 3 printed power supply brackets.
 
     Example: ![alt text](./Photos/IMG_20150227_161250.jpg "Power supply mounting brackets")
 
 18. Place the power supply laying flat on a surface in front of you with the fan side down and the terminal side facing left.
 
 19. Using an M4x10mm screw secure the side of the 2 identical printed brackets to the bottom side of the power supply. This will be the side facing you.
 
     Example: ![alt text](./Photos/IMG_20150227_161341.jpg "Brackets mounted")
 
 20. In the remaining power supply bracket insert 1 M5x8mm button head screw into each of the 2 holes on the extrusion mount side. Thread a T-Slot nut on each screw.
 
     Example: ![alt text](./Photos/IMG_20150227_163152.jpg "Screws inserted into the bracket")
 
 21. On the side of the power supply facing away from you, top side, use an M4x8mm screw to secure the remaining printed bracket to the power supply.
 
     Example: ![alt text](./Photos/IMG_20150227_161421.jpg "Bracket installed")
 
 22. Begin installing the power supply by sliding the 2 threaded T-Slot nuts into the rear right vertical extrusion on the left side of the extrusion.
 
     Example: ![alt text](./Photos/IMG_20150227_163237.jpg "Installing the power supply")
              ![alt text](./Photos/IMG_20150227_164151.jpg "Power supply slid down to the back right corner")
 
 23. Now is a great time to check the input voltage.  For the US set the switch to 115V.
 
     Example: ![alt text](./Photos/IMG_20150227_164201.jpg "Setting the voltage")
 
 24. Using the T-Slot nuts installed in the front face of the rear bottom extrusion secure the remaining power supply brackets.
 
     Example: ![alt text](./Photos/IMG_20150227_162033.jpg "Power supply secured")
 
## Z-Gantry

 Parts needed:
    * 8 Openbuilds V-Slot wheel kits
    * 8 1/4" eccentric spacers
    * 8 M5x25mm button head screws
    * 8 M5 15mm OD washer
    * 2 Delrin lead screw nuts (See BOM for part number)
    * 2 12mm lead screws (See BOM for part number")
    * 4 608ZZ bearings
    * 4 8mm shim washers
    * 4 M5x25mm socket head cap screws
    * 4 M5x16mm button head socket cap screws
    * 2 36 tooth pulleys
    * 2 Z Leadscrew top bearing holders
    * 2 Z Leadscrew bottom bearing holders
    * 8 M5x8mm button head screws
    * 4 M5x10mm button head screws

 1. Locate the 2 Z-Gantry angle plates.
 
 2. Using the drawings below, make the necessary cuts and holes to both Z-Gantry Plates.
 
    Drawings: ![alt text](./Drawings/Z-Gantry_Angle_plate_wheel_face.jpg "Wheel Face")
              ![alt text](./Drawings/Z-Gantry_angle_plate_bottom.jpg "Bottom side")
 
 3. This would be a great time to paint the plates if you want to.
 
    Example: ![alt text](./Photos/IMG_20150228_143323.jpg "Painted Z-Gantry Plate")
 
 4. Set one plate aside.
 
 5. With one Z gantry angle plate drilled and prepped (optionally painted) locate 1 M5x25mm button head screw, 1 V-Slot wheel kit 1 M5 15mm OD washer and 1 1/4" eccentric spacer.
 
 6. Assemble the wheel assembly as shown below.
 
    Assembly: ![alt text](./Photos/IMG_20150228_150616.jpg "Step 1")
              ![alt text](./Photos/IMG_20150228_150632.jpg "Step 2")
              ![alt text](./Photos/IMG_20150228_150714.jpg "Step 3")
              ![alt text](./Photos/IMG_20150228_150729.jpg "Step 4")
              ![alt text](./Photos/IMG_20150228_150804.jpg "Step 5")
 
 7. Tighten down the wheel assembly on the z gantry plate until it's snug but still can be adjusted with a box end wrench.
    
 8. Repeat this process for all 4 wheel mounting holes but before tightening down one of the top wheels insert the printed Z end stop tab. Pay attention to which wheel you are putting this on to be sure you want your Z end stop mounted on that side of the Z uprights..
 
    Example: ![alt text](./Photos/IMG_20150228_191827.jpg "Z Endstop tab")
 
 9. Using a bubble level and a box end wrench that fits your eccentric spacer balance the Z gantry plate.  This can take quite a while so be patient and make sure things are level.
 
    Example: ![alt text](./Photos/IMG_20150228_172624.jpg "Example 1")
             ![alt text](./Photos/IMG_20150228_174103.jpg "Example 2")
             ![alt text](./Photos/IMG_20150228_190435.jpg "Example 3")
             ![alt text](./Photos/IMG_20150228_190455.jpg "Example 4")
 
 10. Repeat steps 5 through 9 for the other gantry plate.
 
 11. Locate the 2 20x20mm extrusions measuring 519.5mm in length.
 
     Example: ![alt text](./Photos/IMG_20150228_192204.jpg "Extrusions")
 
 12. Tap each of the end holes on these 2 extrusions using your M5 x .8mm thread tap.
 
 13. Set one extrusion aside for later.
 
 14. Locate 1 M5x10mm button head screw and 1 oversized M5 washer (15mm OD)
 
 15. Line an extrusion up with the single hole at the end of one of the Z gantry plates and thread the screw through the washer, then the gantry plate hole and finally into the end of the 20x20mm extrusion.
 
     Example: ![alt text](./Photos/IMG_20150228_194000.jpg "Extrusion snugged down")
 
 16. Tighten but only until slightly snug.
 
 17. Insert 2 T-Slot nuts in the bottom slot of the extrusion
 
     Example: ![alt text](./Photos/IMG_20150228_204235.jpg "T-Slot nuts")
 
 18. Line these up with the 2 holes in the bottom of the z gantry plate.
 
 19. Thread 1 M5x8mm button head screw through an M5 washer (not oversized)
 
 20. Insert this screw into one of the holes on the bottom of the z gantry plate and into the T-Slot nut.  Snug the connection down but not tight.
 
     Example: ![alt text](./Photos/IMG_20150228_204834.jpg "Bottom of extrusion secured")
 
 21. Repeat steps 19-20 for the other hole in the Z gantry plate on that side.
 
 22. Repeat steps 14 - 21 for the other side of the gantry plate.
 
 23. Insert 2 more T-Slot nuts in the bottom of each 20x20mm extrusion for the other gantry plate.
 
 24. Repeat steps 14-22 for the other gantry plate.
 
 25. Tighten down all of the screws to complete the Z gantry plate/extrusion assembly.
 
     Example: ![alt text](./Photos/IMG_20150228_213300.jpg "Z-Gantry example 1")
              ![alt text](./Photos/IMG_20150228_213315.jpg "Z-Gantry example 2")
 
 26. Locate 1 Delrin leadscrew nut, 2 M5x16mm button head screws, 2 M5 lock nuts and 4 M5 standard washers.
 
     Example: ![alt text](./Photos/IMG_20150301_003325.jpg "Leadscrew hardware")
 
 27. Place 1 washer on each button head screw and feed each screw through a small hole in the center of one of the gantry plates.
 
     Example: ![alt text](./Photos/IMG_20150301_003900.jpg "Gantry screws in place")
              ![alt text](./Photos/IMG_20150301_003934.jpg "Gantry screws in place")
 
 28. Feed the long end of the delrin nut through the gantry plate's big hole between the 2 screws aligned with the screws and seat it firmly.
 
     Example: ![alt text](./Photos/IMG_20150301_004109.jpg "Delrin nut in place")
 
 29. Using the remaining 2 washers and lock nuts secure the delrin leadscrew nut but do not tighten things down yet.
 
     Example: ![alt text](./Photos/IMG_20150301_004218.jpg "Secured")
 
 30. Repeat steps 27-29 for the other Z-Gantry plate.
 
 31. Print the heat spreader template and tape it together taking care to make sure the lines are aligned properly.  Make sure you print it raw and do not fit to page.
 
     Template: [Heat Spreader Template](./Templates/Aluminum_Heat_Spreader_Paper_Template.pdf)
     
     Example: ![alt text](./Photos/IMG_20150301_012206.jpg "Heat spreader template")
     
 32. Tape the heat spreader template down to the heat spreader and use the template to place your center punch to mark each hole.
 
 33. Drill each hole with a 5mm drill bit.
 
 34. Place the aluminum heat spreader into the mdf insulator board and use the heat spreader as a drill guide to drill the insulator board.
 
 35. Align the holes in the insulator board and heat spreader with the 519.5mm 20x20mm extrusions of the Z-Gantry.  Center the insulator board between the 2 gantry plates and clamp them together.
 
 36. Using the insulator and heat spreader as a drill guide, drill the 5mm holes in the 4 corners of the heat spreader.
 
 37. Remove the clamps and lay the heat spreader on a flat surface.
 
 38. Using a countersinking bit or a larger drill bit that is wider than the head of the M5 flat head screws drill countersinks for all 6 holes of the heat spreader. Make sure that the countersink is deep enough to keep the head of the flat head M5 screws below the surface of the aluminum heat spreader or you risk cracking the corner of the glass that clips on top.
 
     Example: ![alt text](./Photos/IMG_20150301_022653.jpg "Counter sunk hole")
              ![alt text](./Photos/IMG_20150301_103824.jpg "All holes done")
 
 39. Using a larger bit than the original 5mm, I'd say 6 or 7mm, drill out the 4 holes in the 519.5mm 20x20 extrusions to allow the heated bed adjustment to move without binding.
 
 40. Set the gantry assembly aside for now.
 
 41. Locate 4 M5x70mm flat head hex screws, 2 M5x30mm flat head hex screws, 6 M5 nylon lock nuts and 6 M5 oversized washers (15mm OD)
 
     Example: ![alt text](./Photos/IMG_20150301_140203.jpg "Hardware")
 
 42. Lay the MDF insulator board flat with the top of the board facing up.  
 
 43. Position the 380mm square silicone heater in the center of the insulator board with the adhesive side up.
 
 44. Remove the adhesive backing.
 
 45. Thoroughly clean the back side of the aluminum heat spreader to ensure proper adhesion.
 
 46. Place the aluminum heat spreader on top of the heater pad taking great care to align the holes of the heat spreader with the holes in the insulator board.
 
 47. Press down firmly all over the heat spreader to ensure you have adhesion of the silicone heater to the aluminum heat spreader.
 
 48. Select one corner of the aluminum heat spreader and insert 1 M5x70mm flat head screw through the 5mm hole.
     
     Example: ![alt text](./Photos/IMG_20150301_141355.jpg "Screw inserted")
     
 49. On the back side of the MDF insulator board slide 1 M5 oversized washer over the end of the screw and seat it against the MDF insulator board.
 
     Example: ![alt text](./Photos/IMG_20150301_141449.jpg "Washer installed")
 
 50. Thread one M5 nylon lock nut on the end of the screw and tighten down.
 
     Example: ![alt text](./Photos/IMG_20150301_141512.jpg "Lock nut started")
              ![alt text](./Photos/IMG_20150301_141619.jpg "Lock nut tightened")
 
 51. Repeat steps 48 - 50 for each of the other 3 corners of the aluminum heat spreader.
 
 52. Select one of the middle holes in the heat spreader.
 
 53. Insert 1 M5x30mm flat head screw through the hole.
 
     Example: ![alt text](./Photos/IMG_20150301_142222.jpg "Screw inserted")
 
 54. On the back side of the MDF insulator board slide 1 M5 oversized washer over the end of the screw and seat it against the MDF insulator board.
 
     Example: ![alt text](./Photos/IMG_20150301_142237.jpg "Washer installed")
 
 55. Thread one M5 nylon lock nut on the end of the screw and tighten down.
 
     Example: ![alt text](./Photos/IMG_20150301_142252.jpg "Lock nut started")
              ![alt text](./Photos/IMG_20150301_142352.jpg "Lock nut tightened")
 
 56. Repeat steps 52 - 53 for the other middle hole of the aluminum heat spreader.
 
 57. Set this assembly aside for later use.
 
 58. Locate the printed parts "Z Leadscrew Bearing Holder Base" and "Z Leadscrew Bearing Holder Top", there should be 2 of each.
 
 59. Insert 1 608ZZ 8x22x7 bearing in each piece.
 
     **TIPS**
     
      * If the bearing won't fit because the hole it too tight then use a q-tip and acetone to wet the inside walls of the seating surface.  Repeat this until the walls are soft enough to allow you to press fit the bearings.
      * If the bearing fits but is loose then use thin kapton tape wrapped around the bearing evenly to shim the bearing into the holder.
 
 59. Locate 2 36 tooth GT2 pulleys, 4 8mm shim washers and 1 1164mm loop GT2 Belt